#include "Fuzzer/HammeringPattern.hpp"

void to_json(nlohmann::json &j, const HammeringPattern &p) {
  std::vector<AGGRESSOR_ID_TYPE> agg_ids;
  for (const auto &agg : p.accesses) agg_ids.push_back(agg.id);

  j = nlohmann::json{{"id", p.instance_id},
                     {"base_period", p.base_period},
//                     {"accesses", p.accesses},
                     {"access_ids", agg_ids},
                     {"agg_access_patterns", p.agg_access_patterns},
                     {"address_mappings", p.address_mappings}
  };
}

void from_json(const nlohmann::json &j, HammeringPattern &p) {
  j.at("instance_id").get_to(p.instance_id);
  j.at("base_period").get_to(p.base_period);

  // create exactly one aggressor object for each ID (for now it doesn't matter to have multiple aggressors with the
  // same ID but maybe in the future)
  std::vector<AGGRESSOR_ID_TYPE> agg_ids;
  j.at("accesses_agg_ids").get_to<std::vector<AGGRESSOR_ID_TYPE>>(agg_ids);
  std::unordered_map<AGGRESSOR_ID_TYPE, Aggressor> aggs;
  for (const auto &id : agg_ids) {
    if (aggs.count(id)==0) {
      aggs[id] = Aggressor(id);
    }
    p.accesses.push_back(aggs.at(id));
  }

  j.at("agg_access_patterns").get_to<>(p.agg_access_patterns);
  j.at("address_mappings").get_to<>(p.address_mappings);
}

PatternAddressMapping &HammeringPattern::generate_random_addr_mapping(size_t bank) {
  PatternAddressMapping mapping;
  mapping.randomize_addresses(bank, agg_access_patterns);
  address_mappings.push_back(mapping);
  return address_mappings.back();
}

std::vector<volatile char *> HammeringPattern::get_jittable_accesses_vector(PatternAddressMapping &pattern_address_mapping) {
  // sanity check to make sure that this mapping is valid for this pattern
  bool mapping_exists = false;
  for (auto &pam : address_mappings) {
    if (&pam==&pattern_address_mapping) {
      mapping_exists = true;
      break; // no need to continue loop from here
    }
  }
  if (!mapping_exists) {
    fprintf(stderr,
            "[-] Given PatternAddressMapping not found in this HammeringPattern. "
            "Was this PatternAddressMapping generated by generate_random_addr_mapping before?\n");
  }

  return pattern_address_mapping.export_pattern_for_jitting(accesses, base_period);
}
