#!/usr/bin/env python3

class DimmDb:

    @classmethod
    def get_manufacturer_by_dimm_id(cls, internal_id: int):
        dimm_data = {
            1: 'Samsung/Samsung',
            2: 'GSkill/Samsung',
            3: 'GSkill/Samsung',
            4: 'GSkill/Samsung',
            5: 'GSkill/Samsung',
            6: 'Corsair/Samsung',
            7: 'Corsair/Samsung',
            8: 'Corsair/Samsung',
            9: 'Corsair/Samsung',
            10: 'Patriot/Hynix',
            11: 'Kingston/Kingston',
            12: 'GSkill/Samsung',
            13: 'Samsung/Samsung',
            14: 'Kingston/Kingston',
            15: 'Kingston/Kingston',
            16: 'Kingston/Kingston',
            17: 'Kingston/Samsung',
            18: 'Crucial/Micron',
            19: 'Corsair/Micron',
            20: 'Kingston/Micron',
            21: 'Crucial/Micron',
            22: 'Crucial/Micron',
            23: 'Crucial/Micron',
            24: 'Crucial/Micron',
            25: 'Corsair/Micron',
            26: 'Crucial/',
            27: 'Unknown/Unknown',
            28: 'Corsair/Samsung',
            29: 'Corsair/Samsung',
            30: 'Kingston/Hynix',
            31: 'Kingston/Hynix',
            32: 'Kingston/Hynix',
            33: 'Kingston/Hynix',
            34: 'Samsung/Samsung',
            35: 'Samsung/Samsung',
            36: 'Samsung/Samsung',
            431: 'GSkill/Samsung',
            432: 'Corsair/Micron',
            538: 'Corsair/Samsung',
            539: 'Unknown/Hynix',
            540: 'Samsung/Samsung',
        }
        return dimm_data.get(internal_id)
